name: 🐛 Bug report
description: Report a problem or unexpected behaviour
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Checklist"
      value: |
        - [ ] My problem isn't listed in the [Troubleshooting](https://github.com/vyfor/cord.nvim/wiki/Troubleshooting) section of the wiki
        - [ ] I have looked through [existing issues](https://github.com/vyfor/cord.nvim/issues)
        - [ ] I am aware of the recent [announcements](https://github.com/vyfor/cord.nvim/discussions/categories/announcements)
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "Description of the problem you are facing. You may include any relevant logs, screenshots, etc."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Checkhealth"
      description: "Output of `:checkhealth cord`"
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce (optional)"
      description: "Steps to reproduce the issue with the minimal configuration"
      placeholder: |
        1. `nvim -nu repro.lua`
        2. ...
  - type: textarea
    attributes:
      label: "Expected behavior (optional)"
      description: "What you expected to happen"
  - type: textarea
    attributes:
      label: "Actual behavior (optional)"
      description: "What actually happens."
  - type: textarea
    attributes:
      label: "Minimal configuration"
      description: "Minimal configuration to reproduce the issue"
      render: Lua
      value: |
        vim.env.LAZY_STDPATH = '.repro'
        load(vim.fn.system 'curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua')()

        require('lazy.minit').repro {
          spec = {
            {
              'vyfor/cord.nvim',
              build = ':Cord update',
            },
          },
        }

        -- do anything else you need to do to reproduce the issue
    validations:
      required: true