name: Lua lint and format

on:
  push:
    branches: [ "master" ]
    paths:
      - "lua/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "lua/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Lua
        uses: lunarmodules/luacheck@v1
      
      - name: Format Lua
        if: github.event_name == 'push'
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: lua --color always

      - name: Apply changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "vyfor"
          git config --global user.email "92883017+vyfor@users.noreply.github.com"
          git add -A
          git commit -m "style(stylua): format Lua code" || echo "No changes to commit"
          git push
