name: Luacheck

on:
  push:
    branches: [ "master" ]
    paths:
      - "lua/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "lua/**"

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Lua
        uses: lunarmodules/luacheck@v1