name: LuaRocks

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  luarocks:
    name: LuaRocks Build/Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: nvim-neorocks/luarocks-tag-release@v7
      with:
        detailed_description: |
          Meet the future of rich presence with Cord, the most extensible Discord Rich Presence plugin for Neovim, powered by Rust. 
          Cord offers a wide range of customization options allowing you to create custom and dynamic experiences that adapt to your needs.
          The possibilities are endless, and the only limit is your creativity!
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}