name: Publish Artifacts

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.0'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: i686-unknown-linux-musl

          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install additional targets
        run: rustup target add ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build the binary
        run: |
          cross build --release --target ${{ matrix.target }}
          mkdir -p dist
          ARCH=$(echo ${{ matrix.target }} | cut -d '-' -f 1)
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/cord.exe dist/${ARCH}-windows-cord.exe
          elif [[ "${{ matrix.target }}" == *"linux"* ]]; then
            cp target/${{ matrix.target }}/release/cord dist/${ARCH}-linux-cord
          elif [[ "${{ matrix.target }}" == *"darwin"* ]]; then
            cp target/${{ matrix.target }}/release/cord dist/${ARCH}-darwin-cord
          elif [[ "${{ matrix.target }}" == *"freebsd"* ]]; then
            cp target/${{ matrix.target }}/release/cord dist/${ARCH}-bsd-cord
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/*

  upload-artifacts:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
