name: Lua

on:
  push:
    branches: [ "master" ]
    paths:
      - "lua/**"

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Lua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: lua --color always

      - name: Push changes
        run: |
          git config --global user.name "vyfor"
          git config --global user.email "92883017+vyfor@users.noreply.github.com"
          git add -A
          git commit -m "style: format Lua code" || echo "No changes to commit"
          git push